version: "3"

services:
  postgres:
    image: postgres:16
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres-user # EXAMPLE ONLY CHANGE
      POSTGRES_PASSWORD: postgres-pw #EXAMPLE ONLY CHANGE
      POSTGRES_DB: demo
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./infrastructure/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro

  minio:
    image: quay.io/minio/minio
    command: server /data --console-address :9001
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: minioadmin # EXAMPLE CHANGE
      MINIO_SECRET_KEY: minioadmin # EXAMPLE ONLY CHANGE
      MINIO_ROOT_USER: minioadmin # EXAMPLE ONLY CHANGE
      MINIO_ROOT_PASSWORD: minioadmin #EXAMPLE ONLY CHANGE
    volumes:
      - minio_data:/data

volumes:
  pgdata:
  minio_data:
