"""Add image model changes

Revision ID: fe398d6c3f68
Revises: afe25d12b8be
Create Date: 2025-04-05 19:32:37.812579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe398d6c3f68'
down_revision: Union[str, None] = 'afe25d12b8be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('guid', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guid')
    )
    op.add_column('blog_posts', sa.Column('image_guid', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'blog_posts', 'images', ['image_guid'], ['guid'])
    op.add_column('social_media_posts', sa.Column('image_guid', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'social_media_posts', 'images', ['image_guid'], ['guid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'social_media_posts', type_='foreignkey')
    op.drop_column('social_media_posts', 'image_guid')
    op.drop_constraint(None, 'blog_posts', type_='foreignkey')
    op.drop_column('blog_posts', 'image_guid')
    op.drop_table('images')
    # ### end Alembic commands ###
