apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio
spec:
  refreshInterval: "24h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: minio
    creationPolicy: Owner
  data:
    - secretKey: minio_access_key
      remoteRef:
        key: secret/minio
        property: access_key
    - secretKey: minio_access_key_id
      remoteRef:
        key: secret/minio
        property: access_key_id
    - secretKey: minio_endpoint
      remoteRef:
        key: secret/minio
        property: minio_endpoint

