apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: openai
spec:
  refreshInterval: "24h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: openai
    creationPolicy: Owner
  data:
    - secretKey: openai
      remoteRef:
        key: secret/openai
        property: api_key
