apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres
spec:
  refreshInterval: "24h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: postgres
    creationPolicy: Owner
  data:
    - secretKey: content_db_sync
      remoteRef:
        key: secret/content-db
        property: sync
    - secretKey: content_db_async
      remoteRef:
        key: secret/content-db
        property: async
