apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tavily-search
spec:
  refreshInterval: "24h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: tavily-search
    creationPolicy: Owner
  data:
    - secretKey: tavily-search
      remoteRef:
        key: secret/tavily-search
        property: api_key
