apiVersion: v1
kind: Namespace
metadata:
  name: databases
  labels:
    name: databases

---

apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: content-db
  namespace: databases
spec:
  instances: 3

  bootstrap:
    initdb:
      database: content-server
      owner: content
      postInitTemplateSQL:
        - CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

  storage:
    size: 5Gi

  monitoring:
    enablePodMonitor: true